spring:
  datasource:
    username: root
    password: abc12345678
    url: jdbc:mysql://localhost:3306/admission?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    com.gdut: debug

#打印sql语句
#mybatis-plus:
#  configuration:
#    log-impl:
#      org.apache.ibatis.logging.stdout.StdOutImpl